### ISSUE TITLE
PaymentResponse::authorized() not correctly transmitted

### ISSUE THREAD

**Issue by jankal** [shopware/app-php-sdk#9]
The payment state `authorized` apparently does not exist in Shopware core.

Error message:
```
Illegal transition "authorized" from state "ed6ef84314b14802bd57fcb48b3ad7e8". Possible transitions are: authorize, cancel, do_pay, fail, paid, paid_partially, pay, pay_partially, process_unconfirmed, remind
```

So I suggest changing the state name in [PaymentResponse.php#L47](https://github.com/shopware/app-php-sdk/blob/main/src/Response/PaymentResponse.php#L47) to `authorize` which results in the correct state transition.

Showpare Issuetracker: [NEXT-26749](https://issues.shopware.com/issues/NEXT-26749)

**Comment by shyim** [comment]
Is released https://github.com/shopware/app-php-sdk/releases/tag/1.0.4
